apiVersion: v2
name: vault-postgres-helm
description: A Helm chart to deploy Vault with PostgreSQL as the storage backend.
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: vault
    version: "0.24.0"
    repository: "https://helm.releases.hashicorp.com"
  - name: postgresql
    version: "12.1.2"
    repository: "https://charts.bitnami.com/bitnami"
